server:
  port: 80
  servlet:
    context-path: /map
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lj?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: mysql
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.person.map.bean
  configuration:
    map-underscore-to-camel-case: true
  